name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: apconf  # Checkout into apconf directory

  python-build:
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: apconf/py

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Python tests
        run: poetry run pytest

  go-build:
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: apconf/go

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Run Go tests
        run: go test ./...

